# Generated by Django 4.0.5 on 2022-06-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumptionitem',
            old_name='content',
            new_name='productName',
        ),
    ]
