# Generated by Django 4.0.5 on 2022-06-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_rename_content_consumptionitem_productname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReadeyProductName', models.TextField()),
                ('ApproximateProductLifeMin', models.TextField()),
                ('ApproximateProductLifeMax', models.TextField()),
            ],
        ),
    ]
